-define(BY_SIG, couchdb_indexes_by_sig).
-define(BY_COUNTERS, couchdb_indexes_by_counters).
-define(BY_PID, couchdb_indexes_by_pid).
-define(BY_IDLE, couchdb_indexes_by_idle).
-define(BY_DB, couchdb_indexes_by_db).
